version: '3.3'

services:
   
    db_gestorespacos: 
        image: mysql:5.7.26
        environment:
            MYSQL_DATABASE: db_gestorespacos
            MYSQL_USER: gestorespacos 
            MYSQL_PASSWORD: gestorespacos
            MYSQL_ROOT_PASSWORD: root-password
        ports:
            - 3300:3306
        networks:
            - network_backend

    frontend:
        build: ./client
        ports:
            - 3333:3000

    backend:
        build: 
            context: ./server
        command: ["./wait-for-it.sh", "db_gestorespacos:3306", "--", "mvn", "install"]
        command: ["mvn", "spring-boot:run"]
         
        environment:
            WAIT_HOSTS: mysql:3306
            SPRING_DATASOURCE_URL: jdbc:mysql://db_gestorespacos:3306/db_gestorespacos?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Lisbon
            SPRING_DATASOURCE_USERNAME: gestorespacos
            SPRING_DATASOURCE_PASSWORD: gestorespacos
        ports:
            - 8080:8080
        networks:
            - network_backend
        restart: always

networks:
    network_backend:
        driver: "bridge"
